"""add is_logged column

Revision ID: f1544d11b9d4
Revises: 1ade79ca4631
Create Date: 2025-07-16 15:42:01.583086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1544d11b9d4'
down_revision: Union[str, None] = '1ade79ca4631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "passwords",
        sa.Column("is_logged", sa.Integer, nullable=False, default=0)
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("passwords", "is_logged")
    # ### end Alembic commands ###